version: '3.8'
services:
  db:
    image: postgres
    container_name: client_diary
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

volumes:
  dbdata:

# postgres://admin:password@localhost:5432/database
